# Configuration file for the data processing script
data_path: test/fixtures/mlx-community--SmolLM2-135M-Instruct/model.safetensors
save_path: ~/Desktop/smoltorrent/received_model/model.safetensors
ckpt_root: ~/Desktop/smolcluster/checkpoints

# Number of chunks to split the data into
n_chunks: 10

# Number of worker nodes in the distributed setup
num_workers: 4

# Configuration for the devices in the distributed setup
devices_config:
  master:
   -  host: localhost
      ip: 100.78.120.114
      rank: 0
      port: 5000
  workers:
    - host: pi4-1
      ip: 100.68.124.90
      rank: 1
      port: 5001
    - host: pi4-2
      ip: 100.79.150.107
      rank: 2
      port: 5002
    - host: pi4-3
      ip: 100.105.164.35
      rank: 3
      port: 5003
    - host: pi4-4
      ip: 100.77.162.23
      rank: 4
      port: 8004


