data_path: test/fixtures/mlx-community--SmolLM2-135M-Instruct/model.safetensors
save_path: ~/smolcluster/received_model/model.safetensors
ckpt_root: ~/smolcluster/checkpoints
n_chunks: 10
num_workers: 0
devices_config:
  master:
  - host: localhost
    ip: 100.78.120.114
    rank: 0
    port: 5000
  workers: []
