data_path: test/fixtures/mlx-community--SmolLM2-135M-Instruct/model.safetensors
save_path: ~/smolcluster/received_model/model.safetensors
ckpt_root: ~/smolcluster/checkpoints
n_chunks: 10
num_workers: 3
devices_config:
  master:
  - host: localhost
    ip: 100.78.120.114
    rank: 0
    port: 5000
  workers:
  - host: pi4-3
    ip: 100.105.164.35
    rank: 1
    port: 5001
  - host: pi4-1
    ip: 100.68.124.90
    rank: 2
    port: 5002
  - host: pi4-4
    ip: 100.77.162.23
    rank: 3
    port: 5003
  - host: pi4-2
    ip:  100.79.150.107
    rank: 1
